export const cookies = [
	{
		domain: '.youtube.com',
		expirationDate: 1758134036.882299,
		hostOnly: false,
		httpOnly: false,
		name: '__Secure-1PAPISID',
		path: '/',
		sameSite: 'unspecified',
		secure: true,
		session: false,
		storeId: '1',
		value: 'f_qI2g3VbwU13rl4/Ahy52_CdAJrrWkEMm',
		id: 1
	},
	{
		domain: '.youtube.com',
		expirationDate: 1758134036.88243,
		hostOnly: false,
		httpOnly: true,
		name: '__Secure-1PSID',
		path: '/',
		sameSite: 'unspecified',
		secure: true,
		session: false,
		storeId: '1',
		value:
			'g.a000mwingBbp5l4wKcBEZgStwd9DRHiQddNvnxl5vsTa5_b2ZTjcOTjOXY9krng6ZCREZ6_KCwACgYKAdESARUSFQHGX2MiIx1Hlzn6qzoHSGfxkUfjhBoVAUF8yKoWMDzkkCYzQ9ClBvL8XIkY0076',
		id: 2
	},
	{
		domain: '.youtube.com',
		expirationDate: 1755110912.832037,
		hostOnly: false,
		httpOnly: true,
		name: '__Secure-1PSIDCC',
		path: '/',
		sameSite: 'unspecified',
		secure: true,
		session: false,
		storeId: '1',
		value: 'AKEyXzUuhLToWmn2n8hnzFQOXhMxV178LOayZ-WKAGhMdjkYJ33G0l41yKl5BbswtCteyMxG',
		id: 3
	},
	{
		domain: '.youtube.com',
		expirationDate: 1755110639.859979,
		hostOnly: false,
		httpOnly: true,
		name: '__Secure-1PSIDTS',
		path: '/',
		sameSite: 'unspecified',
		secure: true,
		session: false,
		storeId: '1',
		value: 'sidts-CjEBUFGoh_zsj0RQFocDaV5ehsnqyBPNGWVUdNxxHstiNplmxcyh8F-Mn6CPvNlU07taEAA',
		id: 4
	},
	{
		domain: '.youtube.com',
		expirationDate: 1758134036.882325,
		hostOnly: false,
		httpOnly: false,
		name: '__Secure-3PAPISID',
		path: '/',
		sameSite: 'no_restriction',
		secure: true,
		session: false,
		storeId: '1',
		value: 'f_qI2g3VbwU13rl4/Ahy52_CdAJrrWkEMm',
		id: 5
	},
	{
		domain: '.youtube.com',
		expirationDate: 1758134036.882451,
		hostOnly: false,
		httpOnly: true,
		name: '__Secure-3PSID',
		path: '/',
		sameSite: 'no_restriction',
		secure: true,
		session: false,
		storeId: '1',
		value:
			'g.a000mwingBbp5l4wKcBEZgStwd9DRHiQddNvnxl5vsTa5_b2ZTjcyv71bmPjwVnpFjDbZu8nxgACgYKAQYSARUSFQHGX2MiOX9xJofDBzA5cvEWmmfIqxoVAUF8yKo7vhxDKBDMsUptuZn2AnWE0076',
		id: 6
	},
	{
		domain: '.youtube.com',
		expirationDate: 1755110912.832066,
		hostOnly: false,
		httpOnly: true,
		name: '__Secure-3PSIDCC',
		path: '/',
		sameSite: 'no_restriction',
		secure: true,
		session: false,
		storeId: '1',
		value: 'AKEyXzVqOpeZDRAMBpaFr3BOhitqPa2zDiunm3KjYRyU6s8LZT-YMo-MkreQQS1PP2wyII45OQ',
		id: 7
	},
	{
		domain: '.youtube.com',
		expirationDate: 1755110639.860228,
		hostOnly: false,
		httpOnly: true,
		name: '__Secure-3PSIDTS',
		path: '/',
		sameSite: 'no_restriction',
		secure: true,
		session: false,
		storeId: '1',
		value: 'sidts-CjEBUFGoh_zsj0RQFocDaV5ehsnqyBPNGWVUdNxxHstiNplmxcyh8F-Mn6CPvNlU07taEAA',
		id: 8
	},
	{
		domain: '.youtube.com',
		expirationDate: 1758134036.882243,
		hostOnly: false,
		httpOnly: false,
		name: 'APISID',
		path: '/',
		sameSite: 'unspecified',
		secure: false,
		session: false,
		storeId: '1',
		value: 'G6zNN0wqaAGmNMWj/AfQCpOYGFUYYJCTnH',
		id: 9
	},
	{
		domain: '.youtube.com',
		expirationDate: 1723575740.878733,
		hostOnly: false,
		httpOnly: true,
		name: 'GPS',
		path: '/',
		sameSite: 'unspecified',
		secure: true,
		session: false,
		storeId: '1',
		value: '1',
		id: 10
	},
	{
		domain: '.youtube.com',
		expirationDate: 1758134036.882084,
		hostOnly: false,
		httpOnly: true,
		name: 'HSID',
		path: '/',
		sameSite: 'unspecified',
		secure: false,
		session: false,
		storeId: '1',
		value: 'A1fi723Tyw5l_meIT',
		id: 11
	},
	{
		domain: '.youtube.com',
		expirationDate: 1758134035.190629,
		hostOnly: false,
		httpOnly: true,
		name: 'LOGIN_INFO',
		path: '/',
		sameSite: 'no_restriction',
		secure: true,
		session: false,
		storeId: '1',
		value:
			'AFmmF2swRgIhAOxKJyFl4eyyIwDUkXaseV8nVj3HkK9ptJojTVlQm2rtAiEAz2rK2UKlRRcUMdVkKo35iKGE11REe-JGboPmEYaTWBs:QUQ3MjNmemFpblkyM0I5Y3gzeG42LS1FWTlEZ1NmRXdPaUY2SFFzMnNnRm9QZlF1amVhTnVRTU12ZzQycmlJeFZXQS1qWlNuUGdNeWtINzNYdmZRQkU1RGdNOFJ0dW5qdl9zazFfckxNUEpiZkV5UklSMVR3LVl4bUMwMEk4N2YtT3h1eWdPU1ZhdVdmaEoyUVY3YUhrWXpPMnU5aWRMR21n',
		id: 12
	},
	{
		domain: '.youtube.com',
		expirationDate: 1758134041.360524,
		hostOnly: false,
		httpOnly: false,
		name: 'PREF',
		path: '/',
		sameSite: 'unspecified',
		secure: true,
		session: false,
		storeId: '1',
		value: 'f4=4000000&f6=40000000&tz=Asia.Jakarta',
		id: 13
	},
	{
		domain: '.youtube.com',
		expirationDate: 1758134036.882269,
		hostOnly: false,
		httpOnly: false,
		name: 'SAPISID',
		path: '/',
		sameSite: 'unspecified',
		secure: true,
		session: false,
		storeId: '1',
		value: 'f_qI2g3VbwU13rl4/Ahy52_CdAJrrWkEMm',
		id: 14
	},
	{
		domain: '.youtube.com',
		expirationDate: 1758134036.88241,
		hostOnly: false,
		httpOnly: false,
		name: 'SID',
		path: '/',
		sameSite: 'unspecified',
		secure: false,
		session: false,
		storeId: '1',
		value:
			'g.a000mwingBbp5l4wKcBEZgStwd9DRHiQddNvnxl5vsTa5_b2ZTjcaMr47nRlHXLoxxwworIuzQACgYKAe8SARUSFQHGX2MiRQVilCRSk3qQhHydUhqETBoVAUF8yKqRyG3BpXC6z4e323pX-FRb0076',
		id: 15
	},
	{
		domain: '.youtube.com',
		expirationDate: 1755110912.831927,
		hostOnly: false,
		httpOnly: false,
		name: 'SIDCC',
		path: '/',
		sameSite: 'unspecified',
		secure: false,
		session: false,
		storeId: '1',
		value: 'AKEyXzXC-_zPcRqh3DmA1utqRpI_5fnDTq1_rkmJVMKZ5Y9fglBpElOQ-q1oyBMQhgL_Njq6Vw',
		id: 16
	},
	{
		domain: '.youtube.com',
		expirationDate: 1758134036.882213,
		hostOnly: false,
		httpOnly: true,
		name: 'SSID',
		path: '/',
		sameSite: 'unspecified',
		secure: true,
		session: false,
		storeId: '1',
		value: 'A5CshbtDItYolBGES',
		id: 17
	},
	{
		domain: '.youtube.com',
		expirationDate: 1739125940.878907,
		hostOnly: false,
		httpOnly: true,
		name: 'VISITOR_INFO1_LIVE',
		path: '/',
		sameSite: 'no_restriction',
		secure: true,
		session: false,
		storeId: '1',
		value: 'sS23AByHXvY',
		id: 18
	},
	{
		domain: '.youtube.com',
		expirationDate: 1739125940.878955,
		hostOnly: false,
		httpOnly: true,
		name: 'VISITOR_PRIVACY_METADATA',
		path: '/',
		sameSite: 'no_restriction',
		secure: true,
		session: false,
		storeId: '1',
		value: 'CgJJRBIEGgAgMA%3D%3D',
		id: 19
	},
	{
		domain: '.youtube.com',
		hostOnly: false,
		httpOnly: true,
		name: 'YSC',
		path: '/',
		sameSite: 'no_restriction',
		secure: true,
		session: true,
		storeId: '1',
		value: 'VVuV1xm2uhc',
		id: 20
	}
];
