export const cookies = [
	{
		domain: '.youtube.com',
		expirationDate: 1764006073,
		hostOnly: false,
		httpOnly: false,
		name: '__Secure-1PAPISID',
		path: '/',
		sameSite: 'unspecified',
		secure: true,
		session: false,
		storeId: '1',
		value: 'nkbkgzeVbOFLlkqx/A3G-if1K3TPtwsuT7',
		id: 1
	},
	{
		domain: '.youtube.com',
		expirationDate: 1764006073,
		hostOnly: false,
		httpOnly: true,
		name: '__Secure-1PSID',
		path: '/',
		sameSite: 'unspecified',
		secure: true,
		session: false,
		storeId: '1',
		value:
			'g.a000pQiE9otm09KQiDCvJP38Cy72B4s0UnAKb0VIVCJLL94MlaxZ5Yesmeh3PuQ7dkQvXnGrnwACgYKAU8SARASFQHGX2MihQDh7gHRVYZguwNeT0cC3BoVAUF8yKpzeKLeHS3-gJwhjnf0lIvS0076',
		id: 2
	},
	{
		domain: '.youtube.com',
		expirationDate: 1760982081,
		hostOnly: false,
		httpOnly: true,
		name: '__Secure-1PSIDCC',
		path: '/',
		sameSite: 'unspecified',
		secure: true,
		session: false,
		storeId: '1',
		value: 'AKEyXzWOWZoX9nKzSQGeiLWEG5cZPSnYIbfygYoUKVCvhI16tDDNBWkW9aDFYSVJB8_mApeS',
		id: 3
	},
	{
		domain: '.youtube.com',
		expirationDate: 1760982073,
		hostOnly: false,
		httpOnly: true,
		name: '__Secure-1PSIDTS',
		path: '/',
		sameSite: 'unspecified',
		secure: true,
		session: false,
		storeId: '1',
		value: 'sidts-CjEBQlrA-AMmS9ir55F7D_EWEffQkq6yynvrKBzPyCmJYlC5MGAZcflUTL4HvDgWju_8EAA',
		id: 4
	},
	{
		domain: '.youtube.com',
		expirationDate: 1764006073,
		hostOnly: false,
		httpOnly: false,
		name: '__Secure-3PAPISID',
		path: '/',
		sameSite: 'no_restriction',
		secure: true,
		session: false,
		storeId: '1',
		value: 'nkbkgzeVbOFLlkqx/A3G-if1K3TPtwsuT7',
		id: 5
	},
	{
		domain: '.youtube.com',
		expirationDate: 1764006073,
		hostOnly: false,
		httpOnly: true,
		name: '__Secure-3PSID',
		path: '/',
		sameSite: 'no_restriction',
		secure: true,
		session: false,
		storeId: '1',
		value:
			'g.a000pQiE9otm09KQiDCvJP38Cy72B4s0UnAKb0VIVCJLL94MlaxZugaRi_QP5OHMRH8YQBA4ZwACgYKAUQSARASFQHGX2Mi41fKoGsUf0IURdxXD7EBNhoVAUF8yKppGT9NWL9TiVH0wg2XmrPy0076',
		id: 6
	},
	{
		domain: '.youtube.com',
		expirationDate: 1760982081,
		hostOnly: false,
		httpOnly: true,
		name: '__Secure-3PSIDCC',
		path: '/',
		sameSite: 'no_restriction',
		secure: true,
		session: false,
		storeId: '1',
		value: 'AKEyXzXBmiiYVf9nuY8PsNfUwWldtcYGKK42iBJQA0FygVEiO3nARw9rLhB8Y20L95J1AILthg',
		id: 7
	},
	{
		domain: '.youtube.com',
		expirationDate: 1760982073,
		hostOnly: false,
		httpOnly: true,
		name: '__Secure-3PSIDTS',
		path: '/',
		sameSite: 'no_restriction',
		secure: true,
		session: false,
		storeId: '1',
		value: 'sidts-CjEBQlrA-AMmS9ir55F7D_EWEffQkq6yynvrKBzPyCmJYlC5MGAZcflUTL4HvDgWju_8EAA',
		id: 8
	},
	{
		domain: '.youtube.com',
		expirationDate: 1764006073,
		hostOnly: false,
		httpOnly: false,
		name: 'APISID',
		path: '/',
		sameSite: 'unspecified',
		secure: false,
		session: false,
		storeId: '1',
		value: 'y2tvynhh8juJQtsA/AbAVnFzgGXLhvpNnM',
		id: 9
	},
	{
		domain: '.youtube.com',
		expirationDate: 1729447865,
		hostOnly: false,
		httpOnly: true,
		name: 'GPS',
		path: '/',
		sameSite: 'unspecified',
		secure: true,
		session: false,
		storeId: '1',
		value: '1',
		id: 10
	},
	{
		domain: '.youtube.com',
		expirationDate: 1764006073,
		hostOnly: false,
		httpOnly: true,
		name: 'HSID',
		path: '/',
		sameSite: 'unspecified',
		secure: false,
		session: false,
		storeId: '1',
		value: 'AdkAzFSaP1vD0CaAX',
		id: 11
	},
	{
		domain: '.youtube.com',
		expirationDate: 1764006073,
		hostOnly: false,
		httpOnly: true,
		name: 'LOGIN_INFO',
		path: '/',
		sameSite: 'no_restriction',
		secure: true,
		session: false,
		storeId: '1',
		value:
			'AFmmF2swRQIgLqzZyNvfyusBOMDwiBrZdq3sPVPbACpBqvmwm8NEX_UCIQDtOYvatGwS9QMpsR5DAnpi46NzEGq2ViWTsH2Kdq1fIw:QUQ3MjNmemZmV1JGcENYcmFBdWJqamw5LUpRdk9EMjJVcHloQ0tJcGlSU3RBbWpPLTRlbDNiMGFXNXhPQ3dNWGZGZmw2SEgzaDAzcTdlMDU0ZmJvYVd5Tk9jQXBlY2dpTWo5emJyRlJDVy12OTAtLTMyS21uTGtMN09Ea2p6Y2V3cjNmUnJXeW5vZUJzRFlfZjVPVWNCZlhqQ0lIdEtjOTln',
		id: 12
	},
	{
		domain: '.youtube.com',
		expirationDate: 1764006076,
		hostOnly: false,
		httpOnly: false,
		name: 'PREF',
		path: '/',
		sameSite: 'unspecified',
		secure: true,
		session: false,
		storeId: '1',
		value: 'f4=4000000&f6=40000000&tz=Asia.Jakarta',
		id: 13
	},
	{
		domain: '.youtube.com',
		expirationDate: 1764006073,
		hostOnly: false,
		httpOnly: false,
		name: 'SAPISID',
		path: '/',
		sameSite: 'unspecified',
		secure: true,
		session: false,
		storeId: '1',
		value: 'nkbkgzeVbOFLlkqx/A3G-if1K3TPtwsuT7',
		id: 14
	},
	{
		domain: '.youtube.com',
		expirationDate: 1764006073,
		hostOnly: false,
		httpOnly: false,
		name: 'SID',
		path: '/',
		sameSite: 'unspecified',
		secure: false,
		session: false,
		storeId: '1',
		value:
			'g.a000pQiE9otm09KQiDCvJP38Cy72B4s0UnAKb0VIVCJLL94MlaxZd-KTAhSS6f6uJh4KYSSzngACgYKAcgSARASFQHGX2MiM2A0aP57MdUkJaABvEP9thoVAUF8yKoUsMWaijbIiHYWWskwBmlj0076',
		id: 15
	},
	{
		domain: '.youtube.com',
		expirationDate: 1760982081,
		hostOnly: false,
		httpOnly: false,
		name: 'SIDCC',
		path: '/',
		sameSite: 'unspecified',
		secure: false,
		session: false,
		storeId: '1',
		value: 'AKEyXzUN3jTtaY--rj-0oNKza0KnoQJssF-0FdpylR1sVajx52dMeb7P0NST2mqJbhSySZhU8Q',
		id: 16
	},
	{
		domain: '.youtube.com',
		expirationDate: 1764006073,
		hostOnly: false,
		httpOnly: true,
		name: 'SSID',
		path: '/',
		sameSite: 'unspecified',
		secure: true,
		session: false,
		storeId: '1',
		value: 'Ag1kLQkGrejUZXyHu',
		id: 17
	},
	{
		domain: '.youtube.com',
		expirationDate: 1744998065,
		hostOnly: false,
		httpOnly: true,
		name: 'VISITOR_INFO1_LIVE',
		path: '/',
		sameSite: 'no_restriction',
		secure: true,
		session: false,
		storeId: '1',
		value: 'TgZWiLcva4E',
		id: 18
	},
	{
		domain: '.youtube.com',
		expirationDate: 1744998065,
		hostOnly: false,
		httpOnly: true,
		name: 'VISITOR_PRIVACY_METADATA',
		path: '/',
		sameSite: 'no_restriction',
		secure: true,
		session: false,
		storeId: '1',
		value: 'CgJJRBIEGgAgHQ%3D%3D',
		id: 19
	},
	{
		domain: '.youtube.com',
		hostOnly: false,
		httpOnly: true,
		name: 'YSC',
		path: '/',
		sameSite: 'no_restriction',
		secure: true,
		session: true,
		storeId: '1',
		value: '7PTu9hluH44',
		id: 20
	}
];
